# Generated by Django 2.2.3 on 2021-01-31 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videoCiLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(default='', max_length=100, verbose_name='网页')),
                ('category', models.CharField(default='', max_length=100, verbose_name='类别')),
                ('original_title', models.CharField(default='', max_length=100, verbose_name='片名')),
                ('actress', models.CharField(default='', max_length=100, verbose_name='女优')),
                ('size', models.CharField(default='', max_length=100, verbose_name='大小')),
                ('step_riding', models.CharField(default='', max_length=100, verbose_name='步骑')),
                ('time', models.CharField(default='', max_length=100, verbose_name='时间')),
                ('magnetic_force', models.CharField(default='', max_length=1500, verbose_name='磁力')),
                ('preview_one', models.CharField(default='', max_length=1500, verbose_name='预览1')),
                ('preview_two', models.CharField(default='', max_length=1500, verbose_name='预览2')),
                ('preview_three', models.CharField(default='', max_length=1500, verbose_name='预览3')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '登录场景',
                'verbose_name_plural': '登录场景',
            },
        ),
    ]
